#!/bin/bash
# =============================================================
# DVSA PROJECT - MASTER SCRIPT
# =============================================================

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║      DVSA ICS-344 Security Project — Script Suite        ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo " STEP 0: Edit config.sh with your values (REQUIRED FIRST)"
echo "   nano config.sh"
echo ""
echo " STEP 1: Install tools (run once)"
echo "   bash setup/install_tools.sh && aws configure"
echo ""
echo "────────────────────────────────────────────────────────────"
echo " EXPLOIT   →   FIX   →   VERIFY  (repeat for each lesson)"
echo "────────────────────────────────────────────────────────────"
echo ""
echo " L1+L9  exploit: bash lesson1/exploit.sh  (RCE via node-serialize)"
echo "        fix    : bash fixes/lesson1_apply_fix.sh"
echo "        verify : bash lesson1/verify_fix.sh"
echo ""
echo " L2     exploit: bash lesson2/exploit.sh  (JWT forgery)"
echo "        fix    : apply fixes/lesson2_fix.js in Lambda console"
echo "        verify : bash lesson2/verify_fix.sh"
echo ""
echo " L3     exploit: bash lesson3/exploit.sh  (receipt disclosure)"
echo "        fix    : apply fixes/lesson3_fix.js in Lambda console"
echo "        verify : bash lesson3/verify_fix.sh"
echo ""
echo " L4     exploit: bash lesson4/exploit.sh  (S3 misconfiguration)"
echo "        fix    : bash fixes/lesson4_apply_fix.sh"
echo "        verify : bash lesson4/verify_fix.sh"
echo ""
echo " L5     exploit: bash lesson5/exploit.sh  (broken access control)"
echo "        fix    : apply fixes/lesson5_fix.js in Lambda console"
echo "        verify : bash lesson5/verify_fix.sh"
echo ""
echo " L6     exploit: bash lesson6/exploit.sh  (DoS flood)"
echo "        fix    : bash fixes/lesson6_apply_fix.sh"
echo "        verify : bash lesson6/verify_fix.sh"
echo ""
echo " L7     exploit: bash lesson7/exploit.sh  (over-privileged IAM)"
echo "        fix    : bash lesson7/apply_fix.sh"
echo "        verify : bash lesson7/verify_fix.sh"
echo ""
echo " L8     exploit: bash lesson8/exploit.sh  (race condition)"
echo "        fix    : apply fixes/lesson8_fix.js in Lambda console"
echo "        verify : bash lesson8/verify_fix.sh"
echo ""
echo " L9     exploit: bash lesson9/exploit.sh  (dep audit — see also L1)"
echo "        fix    : bash fixes/lesson1_apply_fix.sh (shared with L1)"
echo "        verify : bash lesson9/verify_fix.sh"
echo ""
echo " L10    exploit: bash lesson10/exploit.sh (unhandled exceptions)"
echo "        fix    : apply fixes/lesson10_fix.js in Lambda console"
echo "        verify : bash lesson10/verify_fix.sh"
echo ""
echo "────────────────────────────────────────────────────────────"
echo " HELPERS"
echo "────────────────────────────────────────────────────────────"
echo ""
echo " Generate Part 9 Tables A+B:"
echo "   bash helpers/generate_tables.sh <1-10|ALL>"
echo ""
echo " Save evidence:"
echo "   bash lesson2/exploit.sh 2>&1 | tee lesson2/output.txt"
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Non-production AWS account only. Never use maliciously. ║"
echo "╚══════════════════════════════════════════════════════════╝"
